### ISSUE TITLE
Error: Cannot find module 'relay-compiler/lib/DotGraphQLParser'

### ISSUE THREAD

**Issue by affixalex** [yusinto/relay-compiler-plus#11]
Hi,

I love the concept here! I ran into this while trying out your examples and I reproduced it in my own project. Admittedly I didn't invest much effort into figuring this out, but I figured I'd drop a note here. Essentially, just `npm i -S relay-compiler-plus` and then trying to run it fails with this error on OSX 10.13. I can provide more info and steps to reproduce if necessary.

**Comment by yusinto** [comment]
Hi @affixalex I ran both examples and they seem to be ok. Which example did you try and run? In the process of trying to reproduce I have upgraded all packages in both examples. Perhaps try pulling latest first, do `rm -rf node_modules` and then try again.

**Comment by affixalex** [comment]
To reproduce easily, you can try this Dockerfile in either of the examples. Most of the build dependencies are useless in this context, so it could probably be reproduce in fewer lines but a `docker build .` reproduces the error for me with either of the examples.

    FROM node:10-alpine
    WORKDIR /src
    # The official image has verbose logging; change it to npm's default
    ENV NPM_CONFIG_LOGLEVEL notice
    ADD package*.json ./
    RUN apk add --no-cache --virtual .build \
        autoconf \
        automake \
        g++ \
        libpng-dev \
        libtool \
        make \
        nasm \
        python \
        git \
      && npm i \
      && apk del .build
    ADD . .
    ENV HOST 0.0.0.0
    ENV PORT 4000
    RUN npm run rcp

This is the same error I encounter on OSX 10.13 with Node 10.5.

**Comment by yusinto** [comment]
@affixalex apologies for the delay. I've found the problem and fixed it in this [branch](https://github.com/yusinto/relay-compiler-plus/tree/node-10-upgrade). This branch also contains package upgrades and other things. Will test soon and publish a release. Thanks for reporting the issue.
