### ISSUE TITLE
Allow custom RelayJSModuleParser.js

### ISSUE THREAD

**Issue by johntran** [yusinto/relay-compiler-plus#2]
Hi there!

I love the idea of this package and would love to use it in my app. I currently I have a forked version of relay-compiler that can go through `.tsx` files and returns a `.js` version of the file so that `relay-compiler` can read the file for `graphql` tags.

Two commits that's in the fork: 

getFileFilter function: https://github.com/ONEHOPEWINE/relay/commit/69c68d5bf1ef166994d10cebc3353a7b78b1be52
parseFile function: 
https://github.com/ONEHOPEWINE/relay/commit/a12b931cefb9edac05e989c993c7b7081008b43a#diff-6843e3b7dfd6e16bf7a6bfd9fcc17344

What would be the best way to support `.tsx` file extension in this package?

Thanks!

**Comment by yusinto** [comment]
I think that's a great idea! Are you able to submit a pr?

**Comment by alloy** [comment]
See https://github.com/facebook/relay/pull/2293

**Comment by johntran** [comment]
Closing this in favor of @alloy's plugin. Great work @yusinto and @alloy!

**Comment by cellis** [comment]
@johntran are you able to use relay-compiler-plus with typescript in this way?
