### ISSUE TITLE
Remove console.log()'s

### ISSUE THREAD

**Issue by hollandThomas** [yusinto/relay-compiler-plus#4]
Hey, first of all thanks for making and open sourcing this library! :)

I was just skimming through the source code when I noticed a `console.log` [here](https://github.com/yusinto/relay-compiler-plus/blob/master/lib/matchQueryMiddleware.js#L25). Unless I'm missing something and this gets stripped in production, using `console.log` in production is [considered harmful™](http://expressjs.com/en/advanced/best-practice-performance.html#do-logging-correctly) which is ironical, seeing that this package seeks to improve performance ;)

Thanks for looking into this!

**Comment by yusinto** [comment]
I'll remove them. Thanks for reporting!

**Comment by yusinto** [comment]
This is now done in v1.6.3. You can set debug = true like so `matchQueryMiddleware(queryMapJson, true)` to view console.logs.
