### ISSUE TITLE
Support passing in extensions

### ISSUE THREAD

**Issue by caffodian** [yusinto/relay-compiler-plus#5]
`relay-compiler` supports passing in `--extensions`, so you can run it if you have a convention of naming files `.jsx` for instance.

In my case, I didn't have much of a convention yet, so I worked around it by just renaming my files, but I may come back to looking at the code here and improving this later.

**Comment by yusinto** [comment]
Hi this is a good idea, should not be too hard to do. I will see if I can submit a PR soon. Thanks.

**Comment by yusinto** [comment]
v1.6.5 now does this. I added jsx support by default, so you don't have to use the extensions flag. You can still specify it for other custom file extensions. Let me know if it works!
